# Generated by Django 3.1.3 on 2021-08-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='session',
            field=models.CharField(blank=True, choices=[('', 'Select Year'), ('2020/2021', '2020/2021')], max_length=100, null=True),
        ),
    ]
